### ISSUE TITLE
djamg to livestream DJ set

### ISSUE THREAD

**Issue by chrishobcroft** [decentralizedcultureroom/musicroom#3]
Writing this issue to connect @victoriapriester with @djamg

djamg / Amogh is a DJ in Bangalore, who is involved with Livepeer.

He is already set up to stream his DJ sets using OBS, and I would like to introduce him as an artist to provide sound for the music room as part of ETHBerlin.

![image](https://user-images.githubusercontent.com/2212651/44308213-642cda00-a3b1-11e8-9126-582888bafac8.png)

The idea would be for him to stream music from Bangalore to livepeer, which audiences in the hackathon in Berlin (and around the world) could listen to.

**Comment by victoriapriester** [comment]
Alright, noted! Ill include him in the program

**Comment by victoriapriester** [comment]
@chrishobcroft 
So he would do a live streaming DJ into the music room? So Ill just tune to his livestream? Or what is the idea?

**Comment by chrishobcroft** [comment]
Talk to him. @djamg how can @victoriapriester best communicate with you?

He has lots of energy to participate, and can livestream from Bangalore. It would be a very nice way to connect someone from the previous ETHGlobal hackathon to this one.

Yes, he would maybe do a livestream set that you can use between performances at the venue, to keep the energy high.

But you guys can better work something amazing up together...!

**Comment by mariapaulafn** [comment]
Closing this issue - we cannot have djs - GEMA.
